version: '3.1'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file: ./app.env
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    ports:
      - 5433:5432
    env_file: ./app.env
    volumes:
      - /var/cache/postgres_data:/var/postgresql/data

  postgresql-test:
    image: postgres
    ports:
      - 5434:5433
    env_file: ./app.env
    volumes:
      - /var/cache/postgres_data:/var/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: ./app.env
    ports:
      - 5050:80
    depends_on:
      - postgresql